name: camp-hog
version: 1.0.0
synopsis: blockscope.com
description: Static site generator for blockscope.com
category: web
homepage: https://github.com/blockscope/blockscope/tree/develop#readme
github: BlockScope/blockscope
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
license: BSD3
license-file: LICENSE.md
ghc-options:
- -Wall
extra-source-files:
- package.yaml
- stack.yaml
- LICENSE.md
executables:
  site:
    dependencies:
    - base
    - hakyll
    - pandoc
    - blaze-html
    main: site.hs
    source-dirs: CampHog
tests:
  hlint:
    dependencies:
    - base
    - hakyll
    - pandoc
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - .
    - test-suite-hlint
