# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
extra-source-files:
- package.yaml
- stack.yaml
- LICENSE.md
ghc-options:
- -Wall
executables:
  site:
    dependencies:
    - base
    - hakyll
    - pandoc
    main: site.hs
    source-dirs: CampHog
author: Phil de Joux
maintainer: phil.dejoux@blockscope.com
name: CampHog
synopsis: Company website.
description: Block scope camp hog website.
category: Data
license: BSD3
license-file: LICENSE.md
github: BlockScope/CampHog
tests:
  hlint:
    dependencies:
    - base
    - hakyll
    - pandoc
    - hlint
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: HLint.hs
    source-dirs:
    - .
    - test-suite-hlint
version: '0.1.0'
